export interface Challenge {
  id: string;
  term: string;
  reading: string;
  category: 'it' | 'business' | 'medical' | 'daily';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  hint: string;
  keywords: string[];
  examples: string[];
  ngWords: string[];
}

export const translateChallenges: Challenge[] = [
  {
    id: 'subscription',
    term: 'サブスクリプション',
    reading: 'さぶすくりぷしょん',
    category: 'it',
    difficulty: 'beginner',
    hint: '毎月または毎年お金を払い続ける使い方です。',
    keywords: ['毎月', '払', '使い続け'],
    examples: [
      '毎月お金を払って使い続けるしくみ',
      '決まったお金を定期的に払って使うこと',
      '月ごとに料金を出して続けて使う方法',
    ],
    ngWords: ['サブスクリプション', 'ライセンス'],
  },
  {
    id: 'compliance',
    term: 'コンプライアンス',
    reading: 'こんぷらいあんす',
    category: 'business',
    difficulty: 'intermediate',
    hint: '会社でも個人でも、決まりを守る話です。',
    keywords: ['法律', 'ルール', '守'],
    examples: [
      '法律やルールを守ること',
      '決まりをきちんと守って行動すること',
      'してはいけないことをせず、決まり通りにすること',
    ],
    ngWords: ['コンプライアンス', 'ガバナンス', 'レギュレーション'],
  },
  {
    id: 'agenda',
    term: 'アジェンダ',
    reading: 'あじぇんだ',
    category: 'business',
    difficulty: 'beginner',
    hint: '会議の前に決めておく「話すこと」です。',
    keywords: ['会議', '話し合う', '一覧'],
    examples: [
      '会議で話し合うことの一覧',
      '会議で何を話すかを書いたメモ',
      '会議の予定された話題のリスト',
    ],
    ngWords: ['アジェンダ', 'トピック'],
  },
  {
    id: 'milestone',
    term: 'マイルストーン',
    reading: 'まいるすとーん',
    category: 'business',
    difficulty: 'intermediate',
    hint: '大きな目標へ向かう途中に置く目印です。',
    keywords: ['途中', '目標', '地点'],
    examples: [
      '途中の目標地点',
      'ゴールまでの間にある区切りの目標',
      'ここまで来たと分かる中間の目印',
    ],
    ngWords: ['マイルストーン'],
  },
  {
    id: 'kpi',
    term: 'KPI',
    reading: 'けーぴーあい',
    category: 'business',
    difficulty: 'advanced',
    hint: 'うまくいっているかを数字で見る考え方です。',
    keywords: ['数字', '測', 'うまく'],
    examples: [
      'うまくいっているかを測る数字',
      '目標に近づいているかを見るための数字',
      '進み具合を確かめる大事な数字',
    ],
    ngWords: ['KPI', '指標', 'メトリクス'],
  },
  {
    id: 'onboarding',
    term: 'オンボーディング',
    reading: 'おんぼーでぃんぐ',
    category: 'business',
    difficulty: 'intermediate',
    hint: '新しい人が早く慣れるよう助けることです。',
    keywords: ['新しい', '慣れる', '助け'],
    examples: [
      '新しい人が仕事や場所に慣れるのを助けること',
      '入ったばかりの人を支えて早くなじめるようにすること',
      '新しく来た人にやり方を教えて安心して始めてもらうこと',
    ],
    ngWords: ['オンボーディング', 'フォローアップ'],
  },
  {
    id: 'scalable',
    term: 'スケーラブル',
    reading: 'すけーらぶる',
    category: 'it',
    difficulty: 'advanced',
    hint: '利用者が増えても対応しやすいことです。',
    keywords: ['増えて', '対応', '問題なく'],
    examples: [
      '使う人が増えても問題なく動かせること',
      '人数や量が増えても対応しやすいこと',
      '大きくなっても止まりにくい仕組み',
    ],
    ngWords: ['スケーラブル', 'インフラ', 'リソース'],
  },
  {
    id: 'algorithm',
    term: 'アルゴリズム',
    reading: 'あるごりずむ',
    category: 'it',
    difficulty: 'intermediate',
    hint: 'コンピューターに限らず、順番に進めるやり方です。',
    keywords: ['順番', 'やり方', '手順'],
    examples: [
      '物事を順番に進めるためのやり方',
      '答えを出すための手順',
      'どう進めるかを決めた順番どおりの方法',
    ],
    ngWords: ['アルゴリズム', 'ロジック', 'プログラム'],
  },
  {
    id: 'api',
    term: 'API',
    reading: 'えーぴーあい',
    category: 'it',
    difficulty: 'advanced',
    hint: '別々の仕組みどうしが情報をやりとりする窓口です。',
    keywords: ['仕組み', '情報', 'やりとり'],
    examples: [
      '別の仕組みどうしで情報をやりとりするための窓口',
      '機械同士が話すときの受け渡し口',
      'ほかの道具とつなぐための決まり',
    ],
    ngWords: ['API', 'インターフェース'],
  },
  {
    id: 'cloud',
    term: 'クラウド',
    reading: 'くらうど',
    category: 'it',
    difficulty: 'beginner',
    hint: '自分の機械の中ではなく、ネットの向こう側で使うものです。',
    keywords: ['ネット', '向こう', '使う'],
    examples: [
      '自分の機械ではなくネットの向こうで使う仕組み',
      'インターネット上にある場所を使うこと',
      '手元ではなく遠くの場所で動くものを借りて使うこと',
    ],
    ngWords: ['クラウド', 'サーバー', 'オンライン'],
  },
  {
    id: 'evidence',
    term: 'エビデンス',
    reading: 'えびでんす',
    category: 'medical',
    difficulty: 'intermediate',
    hint: '思い込みではなく、確かな根拠のことです。',
    keywords: ['根拠', '確か', '証拠'],
    examples: [
      'たしかだと言える根拠',
      '本当だと確かめるための証拠',
      'そう言える理由になる確かな材料',
    ],
    ngWords: ['エビデンス', 'エビデンスベース'],
  },
  {
    id: 'informed-consent',
    term: 'インフォームドコンセント',
    reading: 'いんふぉーむどこんせんと',
    category: 'medical',
    difficulty: 'advanced',
    hint: '治療の内容を聞いて、納得してから決めることです。',
    keywords: ['説明', '納得', '同意'],
    examples: [
      '説明を聞いて納得してから同意すること',
      '何をするかを知ったうえで受けると決めること',
      '治療の話を聞いて分かったうえでいいと決めること',
    ],
    ngWords: ['インフォームドコンセント', 'コンセント', 'オペ'],
  },
  {
    id: 'triage',
    term: 'トリアージ',
    reading: 'とりあーじ',
    category: 'medical',
    difficulty: 'advanced',
    hint: '急いで助ける必要が高い人から順番を決めます。',
    keywords: ['急いで', '順番', '助け'],
    examples: [
      '急いで助ける人から順番を決めること',
      'けがや病気の重さを見て先に対応する人を決めること',
      '早く手当てが必要な人を先に選ぶこと',
    ],
    ngWords: ['トリアージ', '優先順位', 'オペレーション'],
  },
  {
    id: 'prognosis',
    term: '予後',
    reading: 'よご',
    category: 'medical',
    difficulty: 'intermediate',
    hint: '病気やけががこの先どうなりそうかです。',
    keywords: ['この先', '良くなる', '見通し'],
    examples: [
      '病気がこの先どうなりそうかの見通し',
      'これから良くなるかどうかの予想',
      '治ったあとや今後の様子の見込み',
    ],
    ngWords: ['予後', '経過', 'リスク'],
  },
  {
    id: 'rehabilitation',
    term: 'リハビリテーション',
    reading: 'りはびりてーしょん',
    category: 'medical',
    difficulty: 'beginner',
    hint: '前のように動けるように、少しずつ練習することです。',
    keywords: ['体', '動ける', '練習'],
    examples: [
      '体を前のように動かせるように練習すること',
      '元の生活に近づけるための少しずつの練習',
      'けがや病気のあとにできることを増やすための訓練',
    ],
    ngWords: ['リハビリテーション', 'リハビリ'],
  },
  {
    id: 'synergy',
    term: 'シナジー',
    reading: 'しなじー',
    category: 'business',
    difficulty: 'advanced',
    hint: '一緒にやることで、別々より大きな力が出ることです。',
    keywords: ['一緒', '大きな力', '生まれる'],
    examples: [
      '一緒にやることで別々より大きな力が出ること',
      '力を合わせてもっと良い結果が生まれること',
      '組み合わせることで一人ずつより強くなること',
    ],
    ngWords: ['シナジー', 'コラボ'],
  },
  {
    id: 'consensus',
    term: 'コンセンサス',
    reading: 'こんせんさす',
    category: 'business',
    difficulty: 'intermediate',
    hint: 'みんなで話して、だいたい同じ考えにそろうことです。',
    keywords: ['みんな', '同じ考え', '納得'],
    examples: [
      'みんながだいたい同じ考えで納得すること',
      '話し合って意見をそろえること',
      'みんなで決めたことに同じ向きで進める状態',
    ],
    ngWords: ['コンセンサス', 'アライメント'],
  },
  {
    id: 'escalation',
    term: 'エスカレーション',
    reading: 'えすかれーしょん',
    category: 'business',
    difficulty: 'intermediate',
    hint: '自分だけでは決められないとき、上の人に相談します。',
    keywords: ['上の人', '相談', '任せる'],
    examples: [
      '自分だけで決めず上の人に相談すること',
      '対応が難しいときに詳しい人や上司へ回すこと',
      '自分の手をこえた問題を別の人に任せること',
    ],
    ngWords: ['エスカレーション', 'マネージャー', 'オーナー'],
  },
  {
    id: 'backlog',
    term: 'バックログ',
    reading: 'ばっくろぐ',
    category: 'it',
    difficulty: 'intermediate',
    hint: 'これからやる予定の仕事をためておく場所です。',
    keywords: ['これから', '仕事', '一覧'],
    examples: [
      'これからやる仕事の一覧',
      'まだ終わっていない作業をためておくリスト',
      '今後やることを並べておくメモ',
    ],
    ngWords: ['バックログ', 'チケット'],
  },
  {
    id: 'default',
    term: 'デフォルト',
    reading: 'でふぉると',
    category: 'daily',
    difficulty: 'beginner',
    hint: '特に変えなければ最初からそうなっている状態です。',
    keywords: ['最初', 'そのまま', '設定'],
    examples: [
      '最初から決まっている設定',
      '特に変えなければそのまま使う形',
      'はじめから入っている決まり',
    ],
    ngWords: ['デフォルト', '初期値'],
  },
  {
    id: 'buffer',
    term: 'バッファ',
    reading: 'ばっふぁ',
    category: 'daily',
    difficulty: 'intermediate',
    hint: '急なことが起きても困らないように、少し余らせておくことです。',
    keywords: ['余裕', '余らせ', '備え'],
    examples: [
      '困らないように少し余裕を持たせておくこと',
      '急なことに備えて空きを残しておくこと',
      '足りなくならないように少し多めに見ておくこと',
    ],
    ngWords: ['バッファ', 'マージン', 'リスクヘッジ'],
  },
];
